version: 1.0.{build}

image: Visual Studio 2017

branches:
  only:
  - develop
  - /release\/.*/
  - master

clone_depth: 1

environment:
  nodejs_version: "LTS"

nuget:
  account_feed: true
  project_feed: true

install:
    - ps: Install-Product node $env:nodejs_version

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'


build_script:
  - cd .\src\Web
  - npm install
  - npm run prod
  - dotnet publish .\ -o __publish
  - 7z a .\Web.zip .\__publish\* .\__publish\**\*
  - cd ..\..

test_script:
  - dotnet build
  - dotnet test --no-build .\tests\Application
  - dotnet test --no-build .\tests\Domain\
  - dotnet test --no-build .\tests\Web\

artifacts:
- path: ./src/Web/Web.zip
  name: Web
  type: WebDeployPackage

deploy:

#- provider: WebDeploy
#  server: https://TODO-staging.scm.azurewebsites.net:443/msdeploy.axd?site=TODO__staging
#  website: TODO__staging
#  username: $TODO__staging
#  password:
#    secure: TODO
#  aspnet_core: true
#  aspnet_core_force_restart: true
#  app_offline: true
#  remove_files: true
#  skip_dirs: \\App_Data;\\.well-known;
#  on:
#    branch:
#    - develop
#    - /release\/.*/

- provider: WebDeploy
  server: https://spk-webapp-template.scm.azurewebsites.net:443/msdeploy.axd?site=spk-webapp-template
  website: spk-webapp-template
  username: $spk-webapp-template
  password:
    secure: f11A8JLgw2zo2nf1ms1Z93m5mZ3MwLABm7xL8++aqT9+3ckpjfJ1Vs0XdIkGh07AsF6r+3RM5YoKGwWFO/5sBg==
  aspnet_core: true
  aspnet_core_force_restart: true
  app_offline: true
  remove_files: true
  skip_dirs: \\App_Data;\\.well-known;
  on:
    branch: master

notifications:
  - provider: Slack
    incoming_webhook:
      secure: XulVWzcYl6EUIlpI6q3QvEBhx8mKB4ia5B5m0HKIRj9o99UZmThYVLMlEl4kK2rT8yvXzTmEKMANzTXzJvW49npQuTz61aWcWwLWpORlLOQ=